### ISSUE TITLE
FreeRTOS functii API 

### ISSUE THREAD

**Issue by norbertlajtai** [etc-sodtr/Ethernet-transfer#2]
Ma poate ajuta cineva cu un manual pentru FreeRTOS care contine descrierea functiilor pentru creare de taskuri, semafoare, etc.? Pe site-ul oficial am gasit manualul, insa costa 30$. Nu inteleg de ce se numeste "FREE" RTOS, daca suportul costa...

**Comment by kcs** [comment]
tocmai se numește FreeRTOS și nu FreeDocumentedOS, pentru că sistemul de operare e gratis
dar pe site ai documentația la toate funcțiile (API reference) în format html

**Comment by norbertlajtai** [comment]
Am observat funcțiile din meniul API reference, însă mi se pare că nu sunt listate toate funcțiile din FreeRTOS. Totuși cred că o să mă descurc cu funcțiile listate pe site. 

Vă mulțumesc pentru răspuns!
